name: ValhallaMMO
version: ${project.version}
main: me.athlaeos.valhallammo.ValhallaMMO
author: Athlaeos
api-version: "1.16"
load: POSTWORLD
softdepend:
- Vault
- WorldEdit
- WorldGuard
- PlaceholderAPI
- DecentHolograms
commands:
  valhalla:
    description: "Main command for all things ValhallaMMO-related"
    aliases: [val]
  skills:
    description: "Shorter command to access the plugin's skill trees"
    aliases: [s]
  partychat:
    description: "Allows a user to toggle party chat, or to send a single message in party chat"
    aliases: [pc]
  party:
    description: "Main command for users to manage their party"
    aliases: [p]
  parties:
    description: "Admin command to manage others' parties"
  partyspy:
    description: "Admin command allowing admins to spy on other people's party chats"
  mining:
    description: "Shorter command for /val profile mining, allowing players to view their mining stats"
  farming:
    description: "Shorter command for /val profile farming, allowing players to view their farming stats"
  fishing:
    description: "Shorter command for /val profile fishing, allowing players to view their fishing stats"
  woodcutting:
    description: "Shorter command for /val profile woodcutting, allowing players to view their woodcutting stats"
  digging:
    description: "Shorter command for /val profile digging, allowing players to view their digging stats"
  lightweapons:
    description: "Shorter command for /val profile light_weapons, allowing players to view their light weapon stats"
  heavyweapons:
    description: "Shorter command for /val profile heavy_weapons, allowing players to view their heavy weapon stats"
  lightarmor:
    description: "Shorter command for /val profile light_armor, allowing players to view their light armor stats"
  heavyarmor:
    description: "Shorter command for /val profile heavy_armor, allowing players to view their heavy armor stats"
  archery:
    description: "Shorter command for /val profile archery, allowing players to view their archery stats"
  smithing:
    description: "Shorter command for /val profile smithing, allowing players to view their smithing stats"
  enchanting:
    description: "Shorter command for /val profile enchanting, allowing players to view their enchanting stats"
  alchemy:
    description: "Shorter command for /val profile alchemy, allowing players to view their alchemy stats"
  power:
    description: "Shorter command for /val profile power, allowing players to view their power stats"
  redeem:
    description: "Exchanges level/exp tokens to any skill level/exp (except power)"
    usage: "/redeem <levels/exp> <skill> <amount>"
  valtop:
    description: "The ValhallaMMO stat leaderboards"
    usage: "/valtop <leaderboard> <player/page>"

permissions:
  valhalla.ignorenoobprotection:
    default: op
    description: "Allows the attacking of players even if their level is much lower than your own"
  valhalla.hardness:
    default: op
    description: "Access to the /val hardness command, which allows the user to change the default hardness of specific block types"
  valhalla.saveall:
    default: op
    description: "Access to the /val saveall command, which allows the user to force the plugin to save all profile progress and recipe changes made"
  valhalla.redeemlevels:
    default: true
    description: "Access to the /redeem levels command, which allows the user to exchange level tokens to any skill level (except power)"
  valhalla.redeemexp:
    default: true
    description: "Access to the /redeem exp command, which allows the user to exchange exp tokens to any skill exp (except power)"
  valhalla.items:
    default: op
    description: "Access to the /valhalla items command, which allows the user to add items to a custom item registry and then use said items in specific recipe modifiers or give them out using a command"
  valhalla.armorsets:
    default: op
    description: "Access to the /valhalla armorsets command, which allows the user to add or edit armor sets which can then be applied to items through modifiers"
  valhalla.give:
    default: op
    description: "Access to the /valhalla give command, which allows users to give themselves or a player a custom item registered in the item registry"
  valhalla.resourcepack:
    default: op
    description: "Allows the user to download the ValhallaMMO resource pack for the server, and to disable or enable certain config settings to be overridden to show the custom textures"
  valhalla.manageparties:
    default: op
    description: "Allows the user to target other people's parties and to manage things like ownership and stats"
  valhalla.partyspy:
    default: op
    description: "Allows the user to use the /partyspy command, allowing them to read along with what the various parties on the server are saying"
  valhalla.createparty:
    default: true
    description: "Allows the user to create their own party"
  valhalla.allrecipes:
    default: op
    description: "All Valhalla custom crafting recipes will be available to the player with this permission"
  valhalla.attribute:
    default: op
    description: "Access to the /valhalla attribute command, which allows the user to apply new attributes to held items"
  valhalla.potioneffect:
    default: op
    description: "Access to the /valhalla potioneffect command, which allows the user to give players custom potion effects"
  valhalla.potionattribute:
    default: op
    description: "Access to the /valhalla potionattribute command, which allows the user to apply custom potion effects to held items"
  valhalla.skills:
    default: true
    description: "Access to the /valhalla skills command, which accesses your skill trees."
  valhalla.help:
    default: op
    description: "Access to the /valhalla help command, which gives descriptions and details on all available commands."
  valhalla.recipes:
    default: op
    description: "Access to the /valhalla recipes command, which gives the user full control over all custom recipes on the server."
  valhalla.loottables:
    default: op
    description: "Access to the /valhalla loot command, which gives the user full control over all loot tables within the plugin."
  valhalla.tool:
    default: op
    description: "Access to the /valhalla tool command, which gives the user access to specialized tools with specific usages. Not intended for players."
  valhalla.modify:
    default: op
    description: "Access to the /valhalla modify command, which allows the user to freely modify held items given the right key and strength."
  valhalla.reward:
    default: op
    description: "Access to the /valhalla reward command, which allows the user to reward a player with a given perk reward."
  valhalla.profile:
    default: true
    description: "Access to the /valhalla profile command, which allows the user to view their own ValhallaMMO stats."
  valhalla.profile.other:
    default: op
    description: "Access to the /valhalla profile command, which allows the user to view anyone's ValhallaMMO stats."
  valhalla.reset.other:
    default: op
    description: "Access to the /valhalla reset command, which soft/hard resets someone's ValhallaMMO progress."
  valhalla.reset:
    default: op
    description: "Access to the /valhalla reset command, which allows the user to only hard reset their own progress"
  valhalla.ignorediminishingreturns:
    default: false
    description: "Allows the user to bypass diminishing returns on EXP gain."
  valhalla.ignorecooldowns:
    default: false
    description: "Allows the user the use abilities freely, cooldown is not applied."
  valhalla.globalbuffs:
    default: op
    description: "Access to the /valhalla globalbuff command, which allows the user to apply global status effects"
  valhalla.reload:
    default: op
    description: "Reloads the plugin's configs into memory, be careful as this also saves changes made to recipes and loot tables before reloading which can cause a lag spike"
  valhalla.exp:
    default: op
    description: "Access to the /valhalla exp command, which allows the user to freely give exp to anyone"
  valhalla.exp.general.#:
    default: false
    description: "Adds (or subtracts) from the player's experience multiplier. valhalla.exp.general.100 gives the player +100% more experience in everything."
  valhalla.exp.smithing.#:
    default: false
    description: "Adds (or subtracts) from the player's smithing experience multiplier. valhalla.exp.smithing.100 gives the player +100% more experience in smithing."
  valhalla.exp.alchemy.#:
    default: false
    description: "Adds (or subtracts) from the player's alchemy experience multiplier. valhalla.exp.alchemy.100 gives the player +100% more experience in alchemy."
  valhalla.exp.enchanting.#:
    default: false
    description: "Adds (or subtracts) from the player's enchanting experience multiplier. valhalla.exp.enchanting.100 gives the player +100% more experience in enchanting."
  valhalla.exp.farming.#:
    default: false
    description: "Adds (or subtracts) from the player's farming experience multiplier. valhalla.exp.farming.100 gives the player +100% more experience in farming."
  valhalla.exp.mining.#:
    default: false
    description: "Adds (or subtracts) from the player's mining experience multiplier. valhalla.exp.mining.100 gives the player +100% more experience in mining."
  valhalla.exp.woodcutting.#:
    default: false
    description: "Adds (or subtracts) from the player's woodcutting experience multiplier. valhalla.exp.woodcutting.100 gives the player +100% more experience in woodcutting."
  valhalla.exp.archery.#:
    default: false
    description: "Adds (or subtracts) from the player's archery experience multiplier. valhalla.exp.archery.100 gives the player +100% more experience in archery."
  valhalla.exp.weapons_light.#:
    default: false
    description: "Adds (or subtracts) from the player's light weapons experience multiplier. valhalla.exp.weapons_light.100 gives the player +100% more experience in light weapons."
  valhalla.exp.weapons_heavy.#:
    default: false
    description: "Adds (or subtracts) from the player's heavy weapons experience multiplier. valhalla.exp.weapons_heavy.100 gives the player +100% more experience in heavy weapons."
  valhalla.exp.armor_light.#:
    default: false
    description: "Adds (or subtracts) from the player's light armor experience multiplier. valhalla.exp.armor_light.100 gives the player +100% more experience in light armor."
  valhalla.exp.armor_heavy.#:
    default: false
    description: "Adds (or subtracts) from the player's heavy armor experience multiplier. valhalla.exp.armor_heavy.100 gives the player +100% more experience in heavy armor."
  valhalla.exp.unarmed.#:
    default: false
    description: "Adds (or subtracts) from the player's unarmed experience multiplier. valhalla.exp.unarmed.100 gives the player +100% more experience in unarmed."

